#!/bin/bash

cd /home/pi/JAM
mkdir -p "/home/pi/jam_logs"

/usr/bin/find /home/pi/jam_logs/ -type f -name 'log*.txt' -mtime +30 -exec rm {} \;
/usr/bin/find /home/pi/jam_logs/ -type f -name 'jam*.log' -mtime +30 -exec rm {} \;

DATE=`date '+%Y%m%d_%H%M'`
/usr/bin/python3 piGUI.py >> "/home/pi/jam_logs/log$DATE.txt" 2>&1
